name: "Test compiling against Java 8, 11 and 16"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testBuilds:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java-version: [8, 11, 16]
    name: "Compile jar against ${{ matrix.java-version }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v2
    - name: "Prepare Java ${{ matrix.java-version }}"
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "${{ matrix.java-version }}"
    - name: "Make build.gradle executable"
      run: "chmod +x gradlew"
    - name: "Build jar with Java ${{ matrix.java-version }}"
      run: "./gradlew shadowJar"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: asts-java${{ matrix.java-version }}
        path: build/libs/*
        retention-days: 0
        compression-level: 6
        overwrite: false
